// SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie <jeff@ocjtech.us>
// SPDX-License-Identifier: MIT

//! Turn CLDR's JSON into the Zig tables this library compiles in.
//!
//! Run by `zig build gen-cldr`, which fetches the `cldr-core`,
//! `cldr-numbers-full` and `cldr-dates-full` packages as lazy dependencies and
//! hands their paths to this program. What it writes goes under `src/cldr/`
//! and is committed.
//!
//! ## Why the output is committed rather than generated by every build
//!
//! Those three packages are 135 MB unpacked. Generating on every build would
//! make every consumer of this library download all of it, on every clean
//! build, to produce files that change only when CLDR issues a release. So the
//! tables are checked in, the packages are lazy dependencies that nothing but
//! this program resolves, and updating to a new CLDR is a deliberate act with
//! a reviewable diff: bump the versions in `build.zig.zon`, run `zig build
//! gen-cldr`, look at what moved.
//!
//! ## Why Zig source and not a data file
//!
//! An `@embedFile` of packed bytes would be smaller in the repository and
//! faster to compile, and it was the first plan. Generated Zig won because of
//! what it costs the *consumer*: each table is a separate declaration in a
//! separate file, so a program that never formats a date never references the
//! date tables, Zig never analyses them, and the linker never emits them.
//! A single blob is one symbol, and one symbol is all-or-nothing.
//!
//! It is also the difference between a diff you can read and a diff you cannot.

const std = @import("std");

const Allocator = std.mem.Allocator;

/// Read the CLDR packages named on the command line and write `src/cldr/`.
pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 4) {
        std.debug.print(
            \\usage: gen_cldr <cldr-core> <cldr-numbers-full> <cldr-dates-full>
            \\
            \\Writes the generated tables to src/cldr/. Run it through the build
            \\system, which knows where the packages are:
            \\
            \\    zig build gen-cldr
            \\
        , .{});
        return error.InvalidArguments;
    }
    var core = try std.Io.Dir.cwd().openDir(io, args[1], .{});
    defer core.close(io);
    var numbers = try std.Io.Dir.cwd().openDir(io, args[2], .{});
    defer numbers.close(io);
    var dates = try std.Io.Dir.cwd().openDir(io, args[3], .{});
    defer dates.close(io);

    var out_dir = try std.Io.Dir.cwd().openDir(io, "src/cldr", .{});
    defer out_dir.close(io);

    try generatePlurals(arena, io, core, out_dir);
    try generateNumbers(arena, io, core, numbers, out_dir);
    try generateDates(arena, io, dates, out_dir);
}

// -- plural rules ------------------------------------------------------------

const Category = enum { zero, one, two, few, many, other };

const Operand = enum { n, i, v, w, f, t, e };

const Range = struct { low: u64, high: u64 };

const Relation = struct {
    operand: Operand,
    modulus: u32 = 0,
    negated: bool = false,
    ranges: []const Range,
};

/// A disjunction of conjunctions.
const Condition = []const []const Relation;

const Rule = struct {
    category: Category,
    condition: Condition,
    /// The `@integer` and `@decimal` sample values CLDR publishes for this
    /// category, expanded from their ranges. They become a test.
    samples: []const []const u8,
};

const RuleSet = struct {
    tag: []const u8,
    rules: []const Rule,
};

/// Write the plural rule tables and CLDR's own samples for them.
fn generatePlurals(
    arena: Allocator,
    io: std.Io,
    core: std.Io.Dir,
    out_dir: std.Io.Dir,
) !void {
    const cardinal = try readRuleSets(arena, io, core, "supplemental/plurals.json", "plurals-type-cardinal");
    const ordinal = try readRuleSets(arena, io, core, "supplemental/ordinals.json", "plurals-type-ordinal");

    try writeRulesFile(arena, io, out_dir, cardinal, ordinal);
    try writeSamplesFile(arena, io, out_dir, cardinal, ordinal);
}

/// Read one plural file and compile every locale's rules out of it.
fn readRuleSets(
    arena: Allocator,
    io: std.Io,
    dir: std.Io.Dir,
    path: []const u8,
    key: []const u8,
) ![]const RuleSet {
    const text = try dir.readFileAlloc(io, path, arena, .limited(16 << 20));
    const parsed = try std.json.parseFromSlice(std.json.Value, arena, text, .{});

    const table = parsed.value.object.get("supplemental").?.object.get(key).?.object;

    var sets: std.ArrayList(RuleSet) = .empty;
    var it = table.iterator();
    while (it.next()) |entry| {
        var rules: std.ArrayList(Rule) = .empty;

        // CLDR writes the categories in the order they must be tried, and the
        // JSON object preserves that order, so the rules are read in place.
        var rule_it = entry.value_ptr.object.iterator();
        while (rule_it.next()) |rule_entry| {
            const category_name = stripPrefix(rule_entry.key_ptr.*, "pluralRule-count-");
            const category = std.meta.stringToEnum(Category, category_name) orelse {
                std.debug.print("unknown plural category: {s}\n", .{category_name});
                return error.UnknownCategory;
            };

            const source = rule_entry.value_ptr.string;
            try rules.append(arena, .{
                .category = category,
                .condition = try parseCondition(arena, conditionOf(source)),
                .samples = try parseSamples(arena, source),
            });
        }

        try sets.append(arena, .{
            .tag = try arena.dupe(u8, entry.key_ptr.*),
            .rules = try rules.toOwnedSlice(arena),
        });
    }

    const owned = try sets.toOwnedSlice(arena);
    // Sorted so that the lookup at run time can be a binary search.
    std.mem.sort(RuleSet, owned, {}, struct {
        /// Order rule sets by tag, so the table can be binary-searched.
        fn lessThan(_: void, a: RuleSet, b: RuleSet) bool {
            return std.mem.order(u8, a.tag, b.tag) == .lt;
        }
    }.lessThan);
    return owned;
}

/// Drop `prefix` from the front of `text` if it is there.
fn stripPrefix(text: []const u8, prefix: []const u8) []const u8 {
    return if (std.mem.startsWith(u8, text, prefix)) text[prefix.len..] else text;
}

/// The condition is everything before the first `@`, which begins the samples.
fn conditionOf(source: []const u8) []const u8 {
    const at = std.mem.indexOfScalar(u8, source, '@') orelse source.len;
    return std.mem.trim(u8, source[0..at], " \t");
}

// -- the CLDR plural rule language -------------------------------------------
//
//     condition     = and_condition ('or' and_condition)*
//     and_condition = relation ('and' relation)*
//     relation      = expr ('=' | '!=') range_list
//     expr          = operand (('mod' | '%') value)?
//     range_list    = (range | value) (',' (range | value))*
//     range         = value '..' value
//
// It has no parentheses and `and` binds tighter than `or`, so every condition
// is a disjunction of conjunctions and needs no tree.

/// Compile a rule's condition into a disjunction of conjunctions.
fn parseCondition(arena: Allocator, source: []const u8) !Condition {
    if (source.len == 0) return &.{};

    var conjunctions: std.ArrayList([]const Relation) = .empty;
    var or_it = std.mem.splitSequence(u8, source, " or ");
    while (or_it.next()) |conjunction_text| {
        var relations: std.ArrayList(Relation) = .empty;
        var and_it = std.mem.splitSequence(u8, conjunction_text, " and ");
        while (and_it.next()) |relation_text| {
            try relations.append(arena, try parseRelation(arena, std.mem.trim(u8, relation_text, " ")));
        }
        try conjunctions.append(arena, try relations.toOwnedSlice(arena));
    }
    return conjunctions.toOwnedSlice(arena);
}

/// Compile one comparison, such as `n % 10 = 2..4`.
fn parseRelation(arena: Allocator, source: []const u8) !Relation {
    const negated = std.mem.indexOf(u8, source, "!=") != null;
    const operator = if (negated) "!=" else "=";
    const split = std.mem.indexOf(u8, source, operator) orelse return error.MalformedRelation;

    const left = std.mem.trim(u8, source[0..split], " ");
    const right = std.mem.trim(u8, source[split + operator.len ..], " ");

    var operand_text = left;
    var modulus: u32 = 0;
    // `mod` is the old spelling of `%`; CLDR's data uses `%` but the grammar
    // still allows both, and accepting both costs one line.
    for ([_][]const u8{ "%", " mod " }) |mod_operator| {
        if (std.mem.indexOf(u8, left, mod_operator)) |at| {
            operand_text = std.mem.trim(u8, left[0..at], " ");
            modulus = try std.fmt.parseInt(u32, std.mem.trim(u8, left[at + mod_operator.len ..], " "), 10);
            break;
        }
    }

    // `c` and `e` are two spellings of the compact decimal exponent.
    const operand = if (std.mem.eql(u8, operand_text, "c"))
        Operand.e
    else
        std.meta.stringToEnum(Operand, operand_text) orelse return error.UnknownOperand;

    var ranges: std.ArrayList(Range) = .empty;
    var it = std.mem.splitScalar(u8, right, ',');
    while (it.next()) |item_text| {
        const item = std.mem.trim(u8, item_text, " ");
        if (std.mem.indexOf(u8, item, "..")) |dots| {
            try ranges.append(arena, .{
                .low = try std.fmt.parseInt(u64, std.mem.trim(u8, item[0..dots], " "), 10),
                .high = try std.fmt.parseInt(u64, std.mem.trim(u8, item[dots + 2 ..], " "), 10),
            });
        } else {
            const value = try std.fmt.parseInt(u64, item, 10);
            try ranges.append(arena, .{ .low = value, .high = value });
        }
    }

    return .{
        .operand = operand,
        .modulus = modulus,
        .negated = negated,
        .ranges = try ranges.toOwnedSlice(arena),
    };
}

// -- samples -----------------------------------------------------------------

/// Expand the `@integer` and `@decimal` sample lists CLDR publishes.
///
/// They are the reason this generator bothers with samples at all: CLDR states
/// which category each of these values belongs to, so every one is a test that
/// the compiled rule and the operand derivation agree with the source of
/// truth. `0~15` is a range and expands; `…` means "and so on" and is dropped.
fn parseSamples(arena: Allocator, source: []const u8) ![]const []const u8 {
    var samples: std.ArrayList([]const u8) = .empty;

    var sections = std.mem.splitScalar(u8, source, '@');
    _ = sections.next(); // the condition
    while (sections.next()) |section| {
        const space = std.mem.indexOfScalar(u8, section, ' ') orelse continue;
        const body = section[space + 1 ..];

        var it = std.mem.splitScalar(u8, body, ',');
        while (it.next()) |item_text| {
            const item = std.mem.trim(u8, item_text, " \t\n");
            if (item.len == 0) continue;
            if (std.mem.eql(u8, item, "…") or std.mem.eql(u8, item, "...")) continue;

            if (std.mem.indexOfScalar(u8, item, '~')) |tilde| {
                try expandRange(arena, &samples, item[0..tilde], item[tilde + 1 ..]);
            } else {
                try samples.append(arena, try arena.dupe(u8, item));
            }
        }
    }

    return samples.toOwnedSlice(arena);
}

/// Expand `0.0~1.5` into 0.0, 0.1, ... 1.5.
///
/// The step is one unit in the last place shown, and the endpoints keep their
/// number of decimal places, because that is what makes the sample a sample:
/// `1.0` and `1` are different operands and CLDR means the one it wrote.
fn expandRange(
    arena: Allocator,
    samples: *std.ArrayList([]const u8),
    low_text: []const u8,
    high_text: []const u8,
) !void {
    const places = decimalPlaces(low_text);
    if (places != decimalPlaces(high_text)) return error.MismatchedSampleRange;

    const scale = std.math.pow(u64, 10, places);
    const low = try scaledValue(low_text, places);
    const high = try scaledValue(high_text, places);
    if (high < low) return error.MalformedSampleRange;

    // CLDR's ranges are short by construction; the cap is only so that a
    // malformed one cannot fill memory.
    if (high - low > 1000) return error.SampleRangeTooLarge;

    var value = low;
    while (value <= high) : (value += 1) {
        try samples.append(arena, try formatScaled(arena, value, scale, places));
    }
}

/// Write a value scaled by `10^places` back as a decimal with that many
/// places, so that `1` at two places is `"0.01"` and not `"0.1"`.
fn formatScaled(arena: Allocator, value: u64, scale: u64, places: u6) ![]const u8 {
    if (places == 0) return std.fmt.allocPrint(arena, "{d}", .{value});

    var digits: [24]u8 = undefined;
    const fraction = try std.fmt.bufPrint(&digits, "{d}", .{value % scale});

    const zeros = "000000000000000000000000";
    return std.fmt.allocPrint(arena, "{d}.{s}{s}", .{
        value / scale,
        zeros[0 .. @as(usize, places) - fraction.len],
        fraction,
    });
}

/// How many digits `text` has after its decimal point.
fn decimalPlaces(text: []const u8) u6 {
    const dot = std.mem.indexOfScalar(u8, text, '.') orelse return 0;
    return @intCast(text.len - dot - 1);
}

/// Read `text` as an integer scaled by ten to the power of `places`.
fn scaledValue(text: []const u8, places: u6) !u64 {
    const dot = std.mem.indexOfScalar(u8, text, '.') orelse
        return (try std.fmt.parseInt(u64, text, 10)) * std.math.pow(u64, 10, places);
    const integer = try std.fmt.parseInt(u64, text[0..dot], 10);
    const fraction = try std.fmt.parseInt(u64, text[dot + 1 ..], 10);
    return integer * std.math.pow(u64, 10, places) + fraction;
}

// -- writing the tables ------------------------------------------------------

/// Write `src/cldr/plurals.zig`.
fn writeRulesFile(
    arena: Allocator,
    io: std.Io,
    out_dir: std.Io.Dir,
    cardinal: []const RuleSet,
    ordinal: []const RuleSet,
) !void {
    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    try writeHeader(w, "The CLDR plural rules, compiled.");
    try w.writeAll(
        \\const plural = @import("../plural.zig");
        \\
        \\const Table = plural.Table;
        \\const Rule = plural.Rule;
        \\const Relation = plural.Relation;
        \\const Range = plural.Range;
        \\
        \\
    );

    try writeTable(w, "cardinal", "Rules for counting things: \"3 files\".", cardinal);
    try w.writeAll("\n");
    try writeTable(w, "ordinal", "Rules for ranking things: \"the 3rd file\".", ordinal);

    try writeFormatted(arena, io, out_dir, "plurals.zig", out.written());
}

/// Write one named table of rule sets, with its sorted key list.
fn writeTable(
    w: *std.Io.Writer,
    name: []const u8,
    description: []const u8,
    sets: []const RuleSet,
) !void {
    try w.print("/// {s}\npub const {s}: Table = .{{\n", .{ description, name });

    try w.writeAll("    .keys = &.{");
    for (sets, 0..) |set, i| {
        if (i % 8 == 0) try w.writeAll("\n       ");
        try w.print(" \"{s}\",", .{set.tag});
    }
    try w.writeAll("\n    },\n");

    try w.writeAll("    .rules = &.{\n");
    for (sets) |set| {
        try w.print("        // {s}\n        &.{{\n", .{set.tag});
        for (set.rules) |rule| {
            try w.print("            .{{ .category = .{t}, .condition = ", .{rule.category});
            try writeCondition(w, rule.condition);
            try w.writeAll(" },\n");
        }
        try w.writeAll("        },\n");
    }
    try w.writeAll("    },\n};\n");
}

/// Write a condition as the nested slice literals the evaluator reads.
fn writeCondition(w: *std.Io.Writer, condition: Condition) !void {
    if (condition.len == 0) {
        try w.writeAll("&.{}");
        return;
    }
    try w.writeAll("&.{");
    for (condition, 0..) |conjunction, i| {
        if (i != 0) try w.writeAll(",");
        try w.writeAll(" &.{");
        for (conjunction, 0..) |relation, j| {
            if (j != 0) try w.writeAll(",");
            try w.print(" .{{ .operand = .{t}", .{relation.operand});
            if (relation.modulus != 0) try w.print(", .modulus = {d}", .{relation.modulus});
            if (relation.negated) try w.writeAll(", .negated = true");
            try w.writeAll(", .ranges = &.{");
            for (relation.ranges, 0..) |range, k| {
                if (k != 0) try w.writeAll(",");
                try w.print(" .{{ .low = {d}, .high = {d} }}", .{ range.low, range.high });
            }
            try w.writeAll(" } }");
        }
        try w.writeAll(" }");
    }
    try w.writeAll(" }");
}

/// Write `src/cldr/plural_samples.zig`.
fn writeSamplesFile(
    arena: Allocator,
    io: std.Io,
    out_dir: std.Io.Dir,
    cardinal: []const RuleSet,
    ordinal: []const RuleSet,
) !void {
    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    try writeHeader(w,
        \\CLDR's own sample values for each plural category.
        \\
        \\Every entry is a value CLDR states belongs to that category in that
        \\locale, which makes the whole file a test of the compiled rules and
        \\of the operand derivation they run on. It is compiled only by the
        \\test build.
    );
    try w.writeAll(
        \\const plural = @import("../plural.zig");
        \\
        \\pub const Sample = struct {
        \\    tag: []const u8,
        \\    category: plural.Category,
        \\    /// The value as CLDR wrote it. The digits matter: "1" and "1.0"
        \\    /// are different operands and may be different categories.
        \\    value: []const u8,
        \\};
        \\
        \\
    );

    try writeSamples(w, "cardinal_samples", cardinal);
    try w.writeAll("\n");
    try writeSamples(w, "ordinal_samples", ordinal);

    try writeFormatted(arena, io, out_dir, "plural_samples.zig", out.written());
}

/// Write one named table of samples, and say how many there were.
fn writeSamples(w: *std.Io.Writer, name: []const u8, sets: []const RuleSet) !void {
    var count: usize = 0;
    for (sets) |set| for (set.rules) |rule| {
        count += rule.samples.len;
    };

    try w.print("pub const {s}: []const Sample = &.{{\n", .{name});
    for (sets) |set| {
        for (set.rules) |rule| {
            for (rule.samples) |sample| {
                try w.print(
                    "    .{{ .tag = \"{s}\", .category = .{t}, .value = \"{s}\" }},\n",
                    .{ set.tag, rule.category, sample },
                );
            }
        }
    }
    try w.writeAll("};\n");

    std.debug.print("gen-cldr: {s}: {d} samples across {d} locales\n", .{ name, count, sets.len });
}

/// Write a generated file through `zig fmt`.
///
/// The generator emits Zig that is correct but not canonically formatted --
/// its table rows are one long line each -- and a repository that must pass
/// `zig fmt --check` cannot hold that. Formatting here rather than as a
/// separate build step means the committed file is right the moment it is
/// written, and a malformed emission is caught immediately by the parse rather
/// than by a compile error somewhere else.
fn writeFormatted(
    arena: Allocator,
    io: std.Io,
    dir: std.Io.Dir,
    sub_path: []const u8,
    source: []const u8,
) !void {
    const sentinel = try arena.dupeZ(u8, source);

    var tree = try std.zig.Ast.parse(arena, sentinel, .zig);
    if (tree.errors.len != 0) {
        var stderr_buffer: [4096]u8 = undefined;
        var stderr = std.Io.File.stderr().writer(io, &stderr_buffer);
        for (tree.errors) |parse_error| {
            try stderr.interface.print("{s}: ", .{sub_path});
            try tree.renderError(parse_error, &stderr.interface);
            try stderr.interface.writeByte('\n');
        }
        try stderr.interface.flush();
        return error.GeneratedInvalidZig;
    }

    const formatted = try tree.renderAlloc(arena);
    try dir.writeFile(io, .{ .sub_path = sub_path, .data = formatted });
}

/// Write the licence header and module documentation of a generated file.
fn writeHeader(w: *std.Io.Writer, doc: []const u8) !void {
    try w.writeAll(
        \\// SPDX-FileCopyrightText: © 1991-2026 Unicode, Inc.
        \\// SPDX-License-Identifier: Unicode-3.0
        \\
        \\// Generated by `zig build gen-cldr` from the Unicode Common Locale Data
        \\// Repository. Do not edit: run the generator instead.
        \\//
        \\
    );
    var lines = std.mem.splitScalar(u8, doc, '\n');
    while (lines.next()) |line| {
        if (line.len == 0) try w.writeAll("//!\n") else try w.print("//! {s}\n", .{line});
    }
    try w.writeAll("\n");
}

// -- number symbols and patterns ---------------------------------------------

const NumberLocale = struct {
    tag: []const u8,
    decimal: []const u8,
    group: []const u8,
    minus_sign: []const u8,
    plus_sign: []const u8,
    percent_sign: []const u8,
    nan: []const u8,
    infinity: []const u8,
    /// The ten digits of the locale's default numbering system.
    digits: []const u8,
    minimum_grouping_digits: u8,
    decimal_pattern: NumberPattern,
    percent_pattern: NumberPattern,
    currency_pattern: NumberPattern,
};

const NumberPattern = struct {
    positive_prefix: []const u8 = "",
    positive_suffix: []const u8 = "",
    negative_prefix: ?[]const u8 = null,
    negative_suffix: ?[]const u8 = null,
    primary_grouping: u8 = 0,
    secondary_grouping: u8 = 0,
    minimum_integer_digits: u8 = 1,
    minimum_fraction_digits: u8 = 0,
    maximum_fraction_digits: u8 = 0,
};

/// Write `src/cldr/numbers.zig` from every locale's number data.
fn generateNumbers(
    arena: Allocator,
    io: std.Io,
    core: std.Io.Dir,
    numbers_root: std.Io.Dir,
    out_dir: std.Io.Dir,
) !void {
    const digits_by_system = try readNumberingSystems(arena, io, core);

    var main_dir = try numbers_root.openDir(io, "main", .{ .iterate = true });
    defer main_dir.close(io);

    var locales: std.ArrayList(NumberLocale) = .empty;

    var it = main_dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .directory) continue;
        const path = try std.fmt.allocPrint(arena, "main/{s}/numbers.json", .{entry.name});
        const text = numbers_root.readFileAlloc(io, path, arena, .limited(4 << 20)) catch continue;
        const parsed = try std.json.parseFromSlice(std.json.Value, arena, text, .{});

        const root = parsed.value.object.get("main").?.object;
        const data = root.values()[0].object.get("numbers").?.object;

        const system = data.get("defaultNumberingSystem").?.string;
        const symbols_key = try std.fmt.allocPrint(arena, "symbols-numberSystem-{s}", .{system});
        const symbols = (data.get(symbols_key) orelse continue).object;

        const pattern = struct {
            /// The standard pattern of one format kind for one numbering
            /// system, or the root's if the locale lists none.
            fn get(d: std.json.ObjectMap, comptime kind: []const u8, sys: []const u8, a: Allocator) ![]const u8 {
                const key = try std.fmt.allocPrint(a, kind ++ "Formats-numberSystem-{s}", .{sys});
                return (d.get(key) orelse return "#,##0.###").object.get("standard").?.string;
            }
        };

        try locales.append(arena, .{
            .tag = try arena.dupe(u8, entry.name),
            .decimal = symbols.get("decimal").?.string,
            .group = symbols.get("group").?.string,
            .minus_sign = symbols.get("minusSign").?.string,
            .plus_sign = symbols.get("plusSign").?.string,
            .percent_sign = symbols.get("percentSign").?.string,
            .nan = symbols.get("nan").?.string,
            .infinity = symbols.get("infinity").?.string,
            .digits = digits_by_system.get(system) orelse "0123456789",
            .minimum_grouping_digits = std.fmt.parseInt(
                u8,
                data.get("minimumGroupingDigits").?.string,
                10,
            ) catch 1,
            .decimal_pattern = try parseNumberPattern(arena, try pattern.get(data, "decimal", system, arena)),
            .percent_pattern = try parseNumberPattern(arena, try pattern.get(data, "percent", system, arena)),
            .currency_pattern = try parseNumberPattern(arena, try pattern.get(data, "currency", system, arena)),
        });
    }

    const owned = try locales.toOwnedSlice(arena);
    std.mem.sort(NumberLocale, owned, {}, struct {
        /// Order locales by tag, so the table can be binary-searched.
        fn lessThan(_: void, a: NumberLocale, b: NumberLocale) bool {
            return std.mem.order(u8, a.tag, b.tag) == .lt;
        }
    }.lessThan);

    try writeNumbersFile(arena, io, out_dir, owned);
    std.debug.print("gen-cldr: numbers: {d} locales\n", .{owned.len});
}

/// The ten digits of each numbering system, from `numberingSystems.json`.
///
/// Only the `numeric` systems have digits; the `algorithmic` ones -- Roman
/// numerals, Chinese financial numerals -- are rule-based and are skipped,
/// since no locale has one as its default.
fn readNumberingSystems(arena: Allocator, io: std.Io, core: std.Io.Dir) !std.StringHashMap([]const u8) {
    var map: std.StringHashMap([]const u8) = .init(arena);

    const text = try core.readFileAlloc(io, "supplemental/numberingSystems.json", arena, .limited(1 << 20));
    const parsed = try std.json.parseFromSlice(std.json.Value, arena, text, .{});
    const systems = parsed.value.object.get("supplemental").?.object
        .get("numberingSystems").?.object;

    var it = systems.iterator();
    while (it.next()) |entry| {
        const info = entry.value_ptr.object;
        if (!std.mem.eql(u8, info.get("_type").?.string, "numeric")) continue;
        try map.put(entry.key_ptr.*, info.get("_digits").?.string);
    }
    return map;
}

/// Compile a CLDR number pattern such as `#,##0.00 ¤` or `#,##0.###;(#,##0.###)`.
///
/// The digits are placeholders: `0` is a digit that must be shown and `#` one
/// that is shown only if it is there, so the number of each says what the
/// minimum and maximum widths are. Everything outside that run is literal text
/// to be put before or after the number, apart from `¤` and `%`, which the
/// formatter substitutes.
fn parseNumberPattern(arena: Allocator, source: []const u8) !NumberPattern {
    var self: NumberPattern = .{};

    // A `;` introduces the pattern for negative numbers. Without one, the
    // negative form is the positive one with a minus sign in front.
    const semicolon = std.mem.indexOfScalar(u8, source, ';');
    const positive = if (semicolon) |at| source[0..at] else source;

    const parts = try splitNumberPattern(arena, positive);
    self.positive_prefix = parts.prefix;
    self.positive_suffix = parts.suffix;
    self.primary_grouping = parts.primary_grouping;
    self.secondary_grouping = parts.secondary_grouping;
    self.minimum_integer_digits = parts.minimum_integer_digits;
    self.minimum_fraction_digits = parts.minimum_fraction_digits;
    self.maximum_fraction_digits = parts.maximum_fraction_digits;

    if (semicolon) |at| {
        const negative = try splitNumberPattern(arena, source[at + 1 ..]);
        self.negative_prefix = negative.prefix;
        self.negative_suffix = negative.suffix;
    }

    return self;
}

const PatternParts = struct {
    prefix: []const u8,
    suffix: []const u8,
    primary_grouping: u8,
    secondary_grouping: u8,
    minimum_integer_digits: u8,
    minimum_fraction_digits: u8,
    maximum_fraction_digits: u8,
};

/// Split one subpattern into its affixes and its digit placeholders.
fn splitNumberPattern(arena: Allocator, source: []const u8) !PatternParts {
    const numeric = "#0,.";

    var start: usize = 0;
    while (start < source.len and std.mem.indexOfScalar(u8, numeric, source[start]) == null) {
        // A quoted run in an affix is literal even if it holds a `#`.
        if (source[start] == '\'') {
            start += 1;
            while (start < source.len and source[start] != '\'') start += 1;
        }
        start += 1;
    }
    var end = start;
    while (end < source.len and std.mem.indexOfScalar(u8, numeric, source[end]) != null) end += 1;

    const body = source[start..end];
    const dot = std.mem.indexOfScalar(u8, body, '.') orelse body.len;
    const integer = body[0..dot];
    const fraction = if (dot < body.len) body[dot + 1 ..] else "";

    // Grouping: the digits after the last comma, and those between the last
    // two. They differ in the South Asian pattern `#,##,##0`, which groups the
    // lowest three and then every two.
    var primary: u8 = 0;
    var secondary: u8 = 0;
    if (std.mem.lastIndexOfScalar(u8, integer, ',')) |last| {
        primary = @intCast(integer.len - last - 1);
        const before = integer[0..last];
        secondary = if (std.mem.lastIndexOfScalar(u8, before, ',')) |second|
            @intCast(before.len - second - 1)
        else
            primary;
    }

    return .{
        .prefix = try unquoteAffix(arena, source[0..start]),
        .suffix = try unquoteAffix(arena, source[end..]),
        .primary_grouping = primary,
        .secondary_grouping = if (secondary == 0) primary else secondary,
        .minimum_integer_digits = @intCast(std.mem.count(u8, integer, "0")),
        .minimum_fraction_digits = @intCast(std.mem.count(u8, fraction, "0")),
        .maximum_fraction_digits = @intCast(fraction.len - std.mem.count(u8, fraction, ",")),
    };
}

/// Strip the quoting from an affix. `''` is a literal apostrophe.
fn unquoteAffix(arena: Allocator, source: []const u8) ![]const u8 {
    if (std.mem.indexOfScalar(u8, source, '\'') == null) return source;

    var out: std.ArrayList(u8) = .empty;
    var i: usize = 0;
    while (i < source.len) {
        if (source[i] != '\'') {
            try out.append(arena, source[i]);
            i += 1;
            continue;
        }
        i += 1;
        if (i < source.len and source[i] == '\'') {
            try out.append(arena, '\'');
            i += 1;
            continue;
        }
        while (i < source.len and source[i] != '\'') : (i += 1) try out.append(arena, source[i]);
        if (i < source.len) i += 1;
    }
    return out.toOwnedSlice(arena);
}

/// Write `src/cldr/numbers.zig`.
fn writeNumbersFile(
    arena: Allocator,
    io: std.Io,
    out_dir: std.Io.Dir,
    locales: []const NumberLocale,
) !void {
    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    try writeHeader(w,
        \\The symbols and patterns each locale writes numbers with.
        \\
        \\`keys` is sorted, so a lookup is a binary search; `symbols` and the
        \\three pattern tables run parallel to it.
    );
    try w.writeAll(
        \\const number_format = @import("../number_format.zig");
        \\
        \\const Symbols = number_format.Symbols;
        \\const Pattern = number_format.Pattern;
        \\
        \\pub const keys: []const []const u8 = &.{
        \\
    );
    for (locales, 0..) |locale, i| {
        if (i % 8 == 0) try w.writeAll("\n   ");
        try w.print(" \"{s}\",", .{locale.tag});
    }
    try w.writeAll("\n};\n\n");

    try w.writeAll("pub const symbols: []const Symbols = &.{\n");
    for (locales) |locale| {
        try w.print(
            "    .{{ .decimal = \"{f}\", .group = \"{f}\", .minus_sign = \"{f}\", " ++
                ".plus_sign = \"{f}\", .percent_sign = \"{f}\", .nan = \"{f}\", " ++
                ".infinity = \"{f}\", .digits = \"{f}\" }},\n",
            .{
                escaped(locale.decimal),      escaped(locale.group),
                escaped(locale.minus_sign),   escaped(locale.plus_sign),
                escaped(locale.percent_sign), escaped(locale.nan),
                escaped(locale.infinity),     escaped(locale.digits),
            },
        );
    }
    try w.writeAll("};\n\n");

    for ([_]struct { []const u8, []const u8 }{
        .{ "decimal_patterns", "decimal_pattern" },
        .{ "percent_patterns", "percent_pattern" },
        .{ "currency_patterns", "currency_pattern" },
    }) |pair| {
        const name, const field = pair;
        try w.print("pub const {s}: []const Pattern = &.{{\n", .{name});
        for (locales) |locale| {
            const pattern = if (std.mem.eql(u8, field, "decimal_pattern"))
                locale.decimal_pattern
            else if (std.mem.eql(u8, field, "percent_pattern"))
                locale.percent_pattern
            else
                locale.currency_pattern;
            try writeNumberPattern(w, pattern, locale.minimum_grouping_digits);
        }
        try w.writeAll("};\n\n");
    }

    try writeFormatted(arena, io, out_dir, "numbers.zig", out.written());
}

/// Write one compiled number pattern as a struct literal.
fn writeNumberPattern(w: *std.Io.Writer, pattern: NumberPattern, minimum_grouping_digits: u8) !void {
    try w.print("    .{{ .positive_prefix = \"{f}\", .positive_suffix = \"{f}\"", .{
        escaped(pattern.positive_prefix),
        escaped(pattern.positive_suffix),
    });
    if (pattern.negative_prefix) |p| try w.print(", .negative_prefix = \"{f}\"", .{escaped(p)});
    if (pattern.negative_suffix) |p| try w.print(", .negative_suffix = \"{f}\"", .{escaped(p)});
    try w.print(
        ", .primary_grouping = {d}, .secondary_grouping = {d}, .minimum_grouping_digits = {d}" ++
            ", .minimum_integer_digits = {d}, .minimum_fraction_digits = {d}" ++
            ", .maximum_fraction_digits = {d} }},\n",
        .{
            pattern.primary_grouping,
            pattern.secondary_grouping,
            minimum_grouping_digits,
            pattern.minimum_integer_digits,
            pattern.minimum_fraction_digits,
            pattern.maximum_fraction_digits,
        },
    );
}

/// A string escaped for a Zig source literal.
///
/// CLDR's data is full of characters that cannot be written raw: non-breaking
/// spaces, right-to-left marks, and the odd quote.
fn escaped(text: []const u8) Escaped {
    return .{ .text = text };
}

const Escaped = struct {
    text: []const u8,

    /// `{f}` writes the text escaped for a Zig source literal.
    pub fn format(self: Escaped, w: *std.Io.Writer) std.Io.Writer.Error!void {
        for (self.text) |c| switch (c) {
            '"' => try w.writeAll("\\\""),
            '\\' => try w.writeAll("\\\\"),
            '\n' => try w.writeAll("\\n"),
            '\r' => try w.writeAll("\\r"),
            '\t' => try w.writeAll("\\t"),
            0x20...0x21, 0x23...0x5B, 0x5D...0x7E => try w.writeByte(c),
            else => try w.print("\\x{x:0>2}", .{c}),
        };
    }
};

// -- calendar names and patterns ---------------------------------------------

const DateLocale = struct {
    tag: []const u8,
    months_wide: [12][]const u8,
    months_abbreviated: [12][]const u8,
    months_narrow: [12][]const u8,
    months_standalone_wide: [12][]const u8,
    months_standalone_abbreviated: [12][]const u8,
    months_standalone_narrow: [12][]const u8,
    weekdays_wide: [7][]const u8,
    weekdays_abbreviated: [7][]const u8,
    weekdays_narrow: [7][]const u8,
    weekdays_standalone_wide: [7][]const u8,
    weekdays_standalone_abbreviated: [7][]const u8,
    weekdays_standalone_narrow: [7][]const u8,
    day_periods: [2][]const u8,
    eras: [2][]const u8,
    eras_wide: [2][]const u8,
    date_formats: [4][]const u8,
    time_formats: [4][]const u8,
    datetime_formats: [4][]const u8,
    datetime_at_formats: [4][]const u8,
    available_formats: []const Available,
    hour12: bool,

    const Available = struct {
        skeleton: []const u8,
        pattern: []const u8,
    };
};

/// The field letters this implementation can put in a skeleton.
///
/// CLDR lists formats for a good many more -- flexible day periods, week of
/// year, quarters -- but `DATETIME()` has no option that asks for them, so
/// keeping their entries would be carrying data nothing can reach. This cuts
/// the table by roughly half.
const skeleton_letters = "GyMEdhHms";

const style_names = [4][]const u8{ "full", "long", "medium", "short" };
const weekday_keys = [7][]const u8{ "sun", "mon", "tue", "wed", "thu", "fri", "sat" };

/// Write `src/cldr/dates.zig` from every locale's Gregorian calendar data.
fn generateDates(arena: Allocator, io: std.Io, dates_root: std.Io.Dir, out_dir: std.Io.Dir) !void {
    var main_dir = try dates_root.openDir(io, "main", .{ .iterate = true });
    defer main_dir.close(io);

    var locales: std.ArrayList(DateLocale) = .empty;

    var it = main_dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .directory) continue;
        const path = try std.fmt.allocPrint(arena, "main/{s}/ca-gregorian.json", .{entry.name});
        const text = dates_root.readFileAlloc(io, path, arena, .limited(4 << 20)) catch continue;
        const parsed = try std.json.parseFromSlice(std.json.Value, arena, text, .{});

        const root = parsed.value.object.get("main").?.object;
        const gregorian = root.values()[0].object
            .get("dates").?.object
            .get("calendars").?.object
            .get("gregorian").?.object;

        var locale: DateLocale = undefined;
        locale.tag = try arena.dupe(u8, entry.name);

        // CLDR gives two sets of names. The "format" set is for a name inside
        // a date -- Finnish puts the weekday in the essive there, "keskiviikkona",
        // meaning "on Wednesday" -- and the "stand-alone" set is the name by
        // itself, "keskiviikko". The pattern letter chooses: `E` and `M` take
        // the format names, `c` and `L` the stand-alone ones.
        const months = gregorian.get("months").?.object;
        const months_format = months.get("format").?.object;
        const months_standalone = months.get("stand-alone").?.object;
        for (0..12) |i| {
            var key_buffer: [4]u8 = undefined;
            const key = try std.fmt.bufPrint(&key_buffer, "{d}", .{i + 1});
            locale.months_wide[i] = months_format.get("wide").?.object.get(key).?.string;
            locale.months_abbreviated[i] = months_format.get("abbreviated").?.object.get(key).?.string;
            locale.months_narrow[i] = months_format.get("narrow").?.object.get(key).?.string;
            locale.months_standalone_wide[i] = months_standalone.get("wide").?.object.get(key).?.string;
            locale.months_standalone_abbreviated[i] = months_standalone.get("abbreviated").?.object.get(key).?.string;
            locale.months_standalone_narrow[i] = months_standalone.get("narrow").?.object.get(key).?.string;
        }

        const days = gregorian.get("days").?.object;
        const days_format = days.get("format").?.object;
        const days_standalone = days.get("stand-alone").?.object;
        for (weekday_keys, 0..) |key, i| {
            locale.weekdays_wide[i] = days_format.get("wide").?.object.get(key).?.string;
            locale.weekdays_abbreviated[i] = days_format.get("abbreviated").?.object.get(key).?.string;
            locale.weekdays_narrow[i] = days_format.get("narrow").?.object.get(key).?.string;
            locale.weekdays_standalone_wide[i] = days_standalone.get("wide").?.object.get(key).?.string;
            locale.weekdays_standalone_abbreviated[i] = days_standalone.get("abbreviated").?.object.get(key).?.string;
            locale.weekdays_standalone_narrow[i] = days_standalone.get("narrow").?.object.get(key).?.string;
        }

        const periods = gregorian.get("dayPeriods").?.object.get("format").?.object
            .get("abbreviated").?.object;
        locale.day_periods = .{ periods.get("am").?.string, periods.get("pm").?.string };

        const eras = gregorian.get("eras").?.object;
        const abbreviated = eras.get("eraAbbr").?.object;
        locale.eras = .{ abbreviated.get("0").?.string, abbreviated.get("1").?.string };
        const wide = eras.get("eraNames").?.object;
        locale.eras_wide = .{ wide.get("0").?.string, wide.get("1").?.string };

        const date_formats = gregorian.get("dateFormats").?.object;
        const time_formats = gregorian.get("timeFormats").?.object;
        const datetime_formats = gregorian.get("dateTimeFormats").?.object;
        // CLDR gives two ways of joining a date to a time. The plain one is
        // for a date and a time that merely appear together; the "at time" one
        // is for a date *at* a time, and reads as a sentence -- English's
        // "{1} 'at' {0}", German's "{1} 'um' {0}". ECMA-402 uses the second
        // when both a dateStyle and a timeStyle were asked for, which is what
        // makes `Intl` say "September 9, 2026 at 2:03 PM".
        const at_time = if (gregorian.get("dateTimeFormats-atTime")) |v|
            v.object.get("standard").?.object
        else
            datetime_formats;

        for (style_names, 0..) |style, i| {
            locale.date_formats[i] = patternText(date_formats.get(style).?);
            locale.time_formats[i] = patternText(time_formats.get(style).?);
            locale.datetime_formats[i] = patternText(datetime_formats.get(style).?);
            locale.datetime_at_formats[i] = patternText(at_time.get(style).?);
        }

        // Which clock the locale prefers, read off its own short time format
        // rather than from the supplemental region tables: if it writes `h`
        // there, it is a twelve-hour locale, and no other source can disagree.
        locale.hour12 = std.mem.indexOfScalar(u8, locale.time_formats[3], 'h') != null;

        var available: std.ArrayList(DateLocale.Available) = .empty;
        var format_it = datetime_formats.get("availableFormats").?.object.iterator();
        while (format_it.next()) |format_entry| {
            const skeleton = format_entry.key_ptr.*;
            // Keys like `MMMMW-count-one` are for a different question.
            if (std.mem.indexOfScalar(u8, skeleton, '-') != null) continue;
            if (!isRequestableSkeleton(skeleton)) continue;
            try available.append(arena, .{
                .skeleton = try arena.dupe(u8, skeleton),
                .pattern = patternText(format_entry.value_ptr.*),
            });
        }
        locale.available_formats = try available.toOwnedSlice(arena);

        try locales.append(arena, locale);
    }

    const owned = try locales.toOwnedSlice(arena);
    std.mem.sort(DateLocale, owned, {}, struct {
        /// Order locales by tag, so the table can be binary-searched.
        fn lessThan(_: void, a: DateLocale, b: DateLocale) bool {
            return std.mem.order(u8, a.tag, b.tag) == .lt;
        }
    }.lessThan);

    try writeDatesFile(arena, io, out_dir, owned);
    std.debug.print("gen-cldr: dates: {d} locales\n", .{owned.len});
}

/// The pattern out of a CLDR value.
///
/// Usually the value is the pattern. A handful carry a numbering-system
/// annotation instead and put the pattern under `_value`: Hawaiian's short
/// date is the only one in the Gregorian calendar data, and it is exactly the
/// kind of single exception that would otherwise be found by a panic on some
/// future CLDR release.
fn patternText(value: std.json.Value) []const u8 {
    return switch (value) {
        .string => |text| text,
        .object => |object| object.get("_value").?.string,
        else => unreachable,
    };
}

/// Whether every letter of `skeleton` is one `DATETIME()` can ask for.
fn isRequestableSkeleton(skeleton: []const u8) bool {
    if (skeleton.len == 0) return false;
    for (skeleton) |c| {
        if (std.mem.indexOfScalar(u8, skeleton_letters, c) == null) return false;
    }
    return true;
}

/// Write `src/cldr/dates.zig`.
fn writeDatesFile(arena: Allocator, io: std.Io, out_dir: std.Io.Dir, locales: []const DateLocale) !void {
    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    try writeHeader(w,
        \\The names and patterns each locale writes dates with, from CLDR's
        \\Gregorian calendar data.
        \\
        \\`keys` is sorted, so a lookup is a binary search, and `names` runs
        \\parallel to it.
    );
    try w.writeAll(
        \\const datetime_format = @import("../datetime_format.zig");
        \\
        \\const Names = datetime_format.Names;
        \\const Available = Names.Available;
        \\
        \\pub const keys: []const []const u8 = &.{
        \\
    );
    for (locales, 0..) |locale, i| {
        if (i % 8 == 0) try w.writeAll("\n   ");
        try w.print(" \"{s}\",", .{locale.tag});
    }
    try w.writeAll("\n};\n\n");

    try w.writeAll("pub const names: []const Names = &.{\n");
    for (locales) |locale| {
        try w.print("    // {s}\n    .{{\n", .{locale.tag});
        try writeNameArray(w, "months_wide", &locale.months_wide);
        try writeNameArray(w, "months_abbreviated", &locale.months_abbreviated);
        try writeNameArray(w, "months_narrow", &locale.months_narrow);
        try writeNameArray(w, "months_standalone_wide", &locale.months_standalone_wide);
        try writeNameArray(w, "months_standalone_abbreviated", &locale.months_standalone_abbreviated);
        try writeNameArray(w, "months_standalone_narrow", &locale.months_standalone_narrow);
        try writeNameArray(w, "weekdays_wide", &locale.weekdays_wide);
        try writeNameArray(w, "weekdays_abbreviated", &locale.weekdays_abbreviated);
        try writeNameArray(w, "weekdays_narrow", &locale.weekdays_narrow);
        try writeNameArray(w, "weekdays_standalone_wide", &locale.weekdays_standalone_wide);
        try writeNameArray(w, "weekdays_standalone_abbreviated", &locale.weekdays_standalone_abbreviated);
        try writeNameArray(w, "weekdays_standalone_narrow", &locale.weekdays_standalone_narrow);
        try writeNameArray(w, "day_periods", &locale.day_periods);
        try writeNameArray(w, "eras", &locale.eras);
        try writeNameArray(w, "eras_wide", &locale.eras_wide);
        try writeNameArray(w, "date_formats", &locale.date_formats);
        try writeNameArray(w, "time_formats", &locale.time_formats);
        try writeNameArray(w, "datetime_formats", &locale.datetime_formats);
        try writeNameArray(w, "datetime_at_formats", &locale.datetime_at_formats);
        try w.print("        .hour12 = {},\n", .{locale.hour12});
        try w.writeAll("        .available_formats = &.{\n");
        for (locale.available_formats) |available| {
            try w.print("            .{{ .skeleton = \"{f}\", .pattern = \"{f}\" }},\n", .{
                escaped(available.skeleton),
                escaped(available.pattern),
            });
        }
        try w.writeAll("        },\n    },\n");
    }
    try w.writeAll("};\n");

    try writeFormatted(arena, io, out_dir, "dates.zig", out.written());
}

/// Write one fixed-length array of names as a struct field.
fn writeNameArray(w: *std.Io.Writer, field: []const u8, values: []const []const u8) !void {
    try w.print("        .{s} = .{{", .{field});
    for (values, 0..) |value, i| {
        if (i != 0) try w.writeAll(",");
        try w.print(" \"{f}\"", .{escaped(value)});
    }
    try w.writeAll(" },\n");
}
